app/cookies/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField 
from wtforms.validators import DataRequired, Length


class LoginForm(FlaskForm):
    username = StringField("Username:", 
                           validators=[DataRequired("Це поле обовʼязкове")],
                           render_kw={"class": "form-control"})
    
    password = PasswordField("Password:", 
                             validators=[DataRequired("Це поле обовʼязкове"), 
                                         Length(min=4, max=10)],
                                         render_kw={"class": "form-control"})
    
    remember = BooleanField("Remember me", 
                            render_kw={"class": "form-check-input"})

    submit = SubmitField("Sign In", 
                         render_kw={"class": "btn btn-primary"})

    
class ChangePassword(FlaskForm):
    current_password = PasswordField("Current password:", 
                             validators=[DataRequired("Це поле обовʼязкове"), 
                                         Length(min=4, max=10)],
                                         render_kw={"class": "form-control"})
    new_password = PasswordField("New password:", 
                             validators=[DataRequired("Це поле обовʼязкове"), 
                                         Length(min=4, max=10)],
                                         render_kw={"class": "form-control"})
    submit_password = SubmitField("Change Password", 
                         render_kw={"class": "btn btn-primary"})

app/cookies/__init__.py
from flask import Blueprint

cookies = Blueprint('cookies', __name__, template_folder="templates/cookies")

from . import views

app/cookies/views.py
#!/usr/bin/python3

from flask import flash, redirect, render_template, url_for, make_response, request, session

import os
import json

from .forms import LoginForm
from .forms import ChangePassword

from . import cookies


json_file_path = os.path.join(os.path.dirname(__file__), '../static', 'json', 'users.json')
with open(json_file_path, 'r') as users_file:
    users = json.load(users_file)

@cookies.route('/form', methods=["GET", "POST"])
def form():
    
    form = LoginForm()  

    if form.validate_on_submit():
        name = form.username.data
        password = form.password.data

        if name in users and users[name] == password:
            if form.remember.data == True:
                flash("Вхід виконано. Інформація збережена.", category="success")
                session["username"] = name

                return redirect(url_for("cookies.info"))
                
            else:
                flash("Вхід виконано. Інформація не збережена", category="success")

                return redirect(url_for("portfolio.home"))

        else:
            flash("Вхід не виконано", category="warning")
            return redirect(url_for("cookies.form"))

    return render_template('form.html', form=form)



@cookies.route('/info', methods=["GET", "POST"])
def info():

    form = ChangePassword()

    if session.get("username"):
        cookies = get_cookies_data()
        if request.method == "POST":
 
            cookie_key = request.form.get("cookie_key")
            cookie_value = request.form.get("cookie_value")
            cookie_expiry = request.form.get("cookie_expiry")
            delete_cookie_key = request.form.get("delete_cookie_key")

            if cookie_key and cookie_value and cookie_expiry:
                add_cookie(cookie_key, cookie_value, int(cookie_expiry))
            if delete_cookie_key:
                delete_cookie(delete_cookie_key)

            cookies = get_cookies_data()  
        return render_template('info.html', cookies=cookies, form=form)
    else:
        return redirect(url_for('cookies.form'))


def get_cookies_data():
    cookies = []
    for key, value in request.cookies.items():
        expiry = request.cookies.get(key + "_expires")
        created = request.cookies.get(key + "_created")

        cookies.append((key, value, expiry, created))
    return cookies

@cookies.route('/clear_session', methods=["GET"])
def clear_session():
    session.pop("username", None)
    return redirect(url_for("cookies.form"))

@cookies.route('/add_cookie', methods=["POST"])
def add_cookie():
    if session.get("username"):
        cookie_key = request.form.get("cookie_key")
        cookie_value = request.form.get("cookie_value")
        cookie_expiry = request.form.get("cookie_expiry")

        response = make_response(redirect(url_for("cookies.info")))
        response.set_cookie(cookie_key, cookie_value, max_age=int(cookie_expiry) * 3600) 
        flash("Куки додано.", category="success")
        return response
    else:
        return redirect(url_for('cookies.form'))

@cookies.route('/delete_cookie', methods=["POST"])
def delete_cookie():
    if session.get("username"):
        cookie_key_to_delete = request.form.get("cookie_key_to_delete")
        response = make_response(redirect(url_for("cookies.info")))
        response.delete_cookie(cookie_key_to_delete)
        flash("Куки видалено.", category="success")
        return response
    else:
        return redirect(url_for('cookies.form'))

@cookies.route('/delete_all_cookies', methods=["POST"])
def delete_all_cookies():
    if session.get("username"):
        response = make_response(redirect(url_for("cookies.info")))
        for key in request.cookies:
            response.delete_cookie(key)
        flash("Куки видалено.", category="success")
        return response
    else:
        flash("Куки не видалено.", category="warning")
        return redirect(url_for('cookies.form'))


@cookies.route('/change_password', methods=["POST"])
def change_password():

    form = ChangePassword()

    if form.validate_on_submit():

        if session.get("username"):
            current_password = form.current_password.data
            new_password = form.new_password.data
            username = session["username"]

            json_file_path = os.path.join(os.path.dirname(__file__), 'static', 'json', 'users.json')

            with open(json_file_path, 'r') as users_file:
                users = json.load(users_file)

            if users.get(username) == current_password:
                users[username] = new_password

                with open(json_file_path, 'w') as users_file:
                    json.dump(users, users_file)

                flash("Пароль змінено.", category="success")
                
                return redirect(url_for("cookies.info"))
            
            else:
                flash("Пароль не змінено.", category="warning")

                return redirect(url_for("cookies.info"))
        
        else:
            return redirect(url_for('cookies.form'))
        
    return render_template('info.html', form=form)

app/cookies/templates/cookies/cookie.html
{% extends "base.html" %}

{% block title %} Форма {% endblock %}

{% block content %}
<h1>Welcome userId = {{userId}}</h1>

{% endblock %}

app/cookies/templates/cookies/form.html
{% from 'render_field.html' import render_field %}
{% extends "base.html" %}

{% block title %} Форма {% endblock %}

{% block content %}

<h1>Form page</h1>
<br>
<div class="d-flex justify-content-center align-items-center">
    <div class="mt-4">
        <form action={{url_for("cookies.form")}}  method="POST" novalidate>
            {{ form.csrf_token }}
            {{ render_field(form.username)}}
            {{ render_field(form.password)}}
            <div class="form-check">
                {{form.remember()}} {{form.remember.label()}}
            </div>
            <br>
            <div class="button-container">
                {{form.submit()}}
            </div>
        </form>
    </div>
</div>

{% endblock %}

app/cookies/templates/cookies/info.html
{% from 'render_field.html' import render_field %}
{% extends "base.html" %}

{% block title %} Info page {% endblock %}

{% block content %}
<h1>Info page</h1>
<br>
<br>
<p>Hello, {{ session["username"] }}!</p>
<br>
<div class="container">
    <p class="text-danger">If you want to log out and delete data from the session, click the button:</p>
    <form action="{{ url_for('cookies.clear_session') }}" method="GET">
        <button type="submit" class="btn btn-danger">Log out</button>
    </form>
    <br>
    <br>
    <h2>Add cookie:</h2>
    <br>
    <form action="{{ url_for('cookies.add_cookie') }}" method="POST">
        <div class="form-group">
            <label for="cookie_key">Key:</label>
            <input type="text" class="form-control" id="cookie_key" name="cookie_key" required>
        </div>
        <div class="form-group">
            <label for="cookie_value">Value:</label>
            <input type="text" class="form-control" id="cookie_value" name="cookie_value" required>
        </div>
        <div class="form-group">
            <label for="cookie_expiry">Validity (hours):</label>
            <input type="number" class="form-control" id="cookie_expiry" name="cookie_expiry" required>
        </div>
        <br>
        <button type="submit" class="btn btn-primary">Add</button>
    </form>
    <br>
    <br>
    <h2>Delete cookies:</h2>
    <br>
    <form action="{{ url_for('cookies.delete_cookie') }}" method="POST">
        <div class="form-group">
            <label for="cookie_key_to_delete">Delete key:</label>
            <input type="text" class="form-control" id="cookie_key_to_delete" name="cookie_key_to_delete" required>
        </div>
        <br>
        <button type="submit" class="btn btn-danger">Delete cookies by key</button>
    </form>
    <br>
    <form action="{{ url_for('cookies.delete_all_cookies') }}" method="POST">
        <button type="submit" class="btn btn-danger">Delete all cookies</button>
    </form>
    <br>
    <br>
    <h2>Change Password:</h2>
    <br>
    <form action="{{ url_for('cookies.change_password') }}" method="POST" novalidate>
        {{ form.csrf_token }}
        {{ render_field(form.current_password)}}
        {{ render_field(form.new_password)}}
        <br>
        {{form.submit_password()}}
    </form>
    <br>
    <br>
    <h2>Збережені кукі:</h2>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Ключ</th>
                <th scope="col">Значення</th>
                <th scope="col">Термін дії</th>
                <th scope="col">Час створення</th>
            </tr>
        </thead>
        <tbody>
            {% for key, value, expiry, created in cookies %}
                <tr>
                    <td>{{ key }}</td>
                    <td>{{ value }}</td>
                    <td>{{ expiry }} hours</td>
                    <td>{{ created }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}