app/todo/models.py
from app import db

class Todo(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100))
    complete = db.Column(db.Boolean) 
    description = db.Column(db.Boolean)

app/todo/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired


class TodoForm(FlaskForm):
    title = StringField("Enter a task here: ", 
                         validators=[DataRequired("This field is required.")],
                         render_kw={"class": "form-control me-sm-2"})
    submit_todo = SubmitField("Save",
                         render_kw={"class": "btn btn-primary my-2 my-sm-0"})
    

app/todo/__init__.py
from flask import Blueprint

todo = Blueprint('todo', __name__, template_folder="templates/todo")

from . import views

app/todo/views.py
from flask import flash, redirect, render_template, url_for

from app import db
from .models import Todo
from .forms import TodoForm

from . import todo

@todo.route('/todo', methods=['GET', 'POST'])
def todos():

    form = TodoForm()

    todo_list = Todo.query.all()

    return render_template("todo.html", form=form, todo_list=todo_list)


@todo.route('/add', methods=["POST"])
def add():

    form = TodoForm()

    if form.validate_on_submit():
        title = form.title.data
        new_todo = Todo(title=title, complete=False)
        db.session.add(new_todo)
        db.session.commit()

        flash('Додано.', 'success')
    else:
        flash('Не додано.', 'danger')

    return redirect(url_for("todo.todos"))


@todo.route('/update/<int:todo_id>')
def update(todo_id):

    todo = db.get_or_404(Todo, todo_id)
    todo.complete = not todo.complete
    db.session.commit()

    flash('Оновлено.', 'success')

    return redirect(url_for('todo.todos'))


@todo.route('/delete/<int:todo_id>')
def delete(todo_id):

    todo = db.get_or_404(Todo, todo_id)
    db.session.delete(todo)
    db.session.commit()

    flash('Видалено.', 'success')

    return redirect(url_for('todo.todos'))

app/todo/templates/todo/todo.html
{% from 'render_field.html' import render_field %}
{% extends "base.html" %}

{% block title %} Todo {% endblock %}

{% block content %}
<h1>Todo page</h1>

<div class="d-flex">
    <div class="mt-4 ">
        <form method="post" action="{{ url_for('todo.add') }}" novalidate>
            {{ form.csrf_token }}
            {{ render_field(form.title) }} 
            {{ form.submit_todo() }}
        </form>
    </div>
</div>

<div class="mt-4">
    <table class="table mb-4 text-center">
        <thead>
            <tr>
            <th scope="col">No.</th>
            <th scope="col">Todo item</th>
            <th scope="col">Status</th>
            <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for todo in todo_list %}
            <tr>
            <th scope="row">
                <div class="mt-4 text-center">
                    {{todo.id }}
                </div>
            </th>
            <td>
                <div class="mt-4 text-center">
                    {{ todo.title }}
                </div>
            </td>
            <td>
                <div class="mt-2 text-center">
                    {% if todo.complete == False %}
                    <div class="alert alert-secondary" role="alert">In progress</div>
                    {% else %}
                    <div class="alert alert-success" role="alert">Completed</div>
                    {% endif %}
                </div>
            </td>
            <td>
                <div class="mt-3 text-center">
                    <a class="btn btn-success" href="/update/{{ todo.id }}">Update</a>
                    <a class="btn btn-danger ms-3" href="/delete/{{ todo.id }}">Delete</a>
                </div>
            </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}